name: code_lfa
description: VS Code for Android
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.6.0+22
code_server: 4.103.1
environment:
  sdk: ">=3.3.0 <4.0.0"

# For developers who cannot easily access GitHub, please override git
# dependencies with a local path in pubspec_overrides.yaml, like:
# dependency_overrides: 
#   behavior_api: 
#     path: ../your_local_path/behavior_api 
dependencies:
  archive: ^4.0.7
  async: ^2.11.0
  behavior_api: 
    path: D:/Design/programming/codefa_utils/behavior_api
  cupertino_icons: ^1.0.2
  device_info_plus: ^12.1.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_pty: ^0.4.2
  get: ^4.6.5
  global_repository: 
    path: D:/Design/programming/codefa_utils/global_repository
  intl: 0.20.2
  path: ^1.9.1
  permission_handler: ^12.0.1
  settings: 
    path: D:/Design/programming/codefa_utils/settings
  signale: ^0.0.9
  tar: ^2.0.0
  url_launcher_android: ^6.3.23
  xterm: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
